### PR TITLE
Update graphql dependencies

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Bump 4 dependencies : <br> graphql from 14.0.2 to 14.5.8 <br> graphql-tag from 2.10.3 to 2.12.1 <br> graphql-tools from 4.0.7 to 5.0.0 <br> graphql-type-json from 0.3.1 to 0.3.2 <br> <b>August 12</b>: Rebase after v3.0.1 release, lint fix and rebuild asset
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Build Release pass. Module works as usual after PR applied (don't forget to rebuild asset and clear browser cache before test ;).

### CODE REVIEW

**Comment by M0rgan01** [comment]
Hello @leemyongpakvn :) [package-lock.json](https://github.com/PrestaShop/blockwishlist/blob/dev/package-lock.json) has not been updated ?

**Comment by leemyongpakvn** [comment]
@M0rgan01 I think package-lock.json and 14 assets files will be renewed by [Build & Release workflow](https://github.com/PrestaShop/blockwishlist/blob/dev/.github/workflows/build-release.yml) automatically. QA team will be happier with simple Files changed ;)

**Comment by M0rgan01** [comment]
The CI will not update your package-lock on the repository. It also seems that there are already problems with the lock file on the dev branch.

A command `npm audit` fails because of differences between package.json and package-lock.json.

To avoid this, you should replace `npm install` with an `npm ci` in the workflow :smiley: 

```
jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone PrestaShop for core dependencies
        run: |
          git clone --depth=50 https://github.com/PrestaShop/PrestaShop.git ~/PrestaShop
          rm -rf ~/PrestaShop/modules/blockwishlist
          cd ..
          mv blockwishlist ~/PrestaShop/modules
          ln -s ~/PrestaShop/modules/blockwishlist
          cd blockwishlist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: **npm ci**
```

**Comment by leemyongpakvn** [comment]
@M0rgan01 package.json and package-lock.json will be updated together by this PR. You can create another PR to replace `npm install` by `npm ci` in workflow (I saw someone did it somewhere in this project but don't remember exactly who and when :).

**Comment by M0rgan01** [comment]
Thanks @leemyongpakvn , I'll do it :)

**Review by M0rgan01 — APPROVED** [review]

**Comment by leemyongpakvn** [comment]
Waiting for the result of the [related discussion](https://github.com/PrestaShop/PrestaShop/discussions/32793)

**Comment by leemyongpakva** [comment]
Close in favor of https://github.com/PrestaShop/blockwishlist/pull/250

**Pull request closed without merging**
