### PR TITLE
Fill empty config label by the label in default language

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fill empty config label by the label in default language
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27474
| How to test?      | Cf. issue

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello, 

I tested the PR and I noticed that  

- if a field is empty => in FO the default language is displayed
- the default language is mandatory though
- if a language has not been set then we must fall back to the default language
- you can edit and save all fields without filling in all the languages

Could you please specify the expected behavior p@PrestaShop/product-team?

Thank you,

**Comment by MatShir** [comment]
Thanks @marwachelly, it is the wanted behavior. When a field is mandatory, we use the default language as fallback.

**Comment by marwachelly** [comment]
> Thanks @marwachelly, it is the wanted behavior. When a field is mandatory, we use the default language as fallback.

Thank you @MatShir. So the PR is Ok. :+1:

**Review by marwachelly — APPROVED** [review]
Hello,

PR is tested. Issue is fixed. PR is QA approved.

Thanks, 

- [ ]

**Comment by Progi1984** [comment]
Thanks @marwachelly

**Pull request merged**
