### PR TITLE
Fix filename to hookname relation

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Finishing touch for #132. As the file was moved from hookDisplayHeader to hookDisplayFooter then the file name change should also follow.
| Type?             | refacto
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | Check if module's content is still being loaded in FO footer.
| Possible impacts? | It may brake custom theme's overrides for displayHeader.tpl, although there's no reason to override it anyway.

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
I approve but I think the name was keep for retro compatibility reason.
ping @kpodemski

**Comment by SharakPL** [comment]
> I approve but I think the name was kept for retro compatibility reasons. 

Well, maybe it would be better to use filenames related to files' content, not the hooks they're supposed to be attached to ;)

**Comment by kpodemski** [comment]
I understand the reason, and I agree that we should have a different name for the file. btw. This is BC Break IMHO, because as you've noticed @SharakPL - overrides won't work anymore.

> Well, maybe it would be better to use filenames related to files' content, not the hooks they're supposed to be attached to ;)
> ...as a general rule for modules.

This might be good for this scenario, but if you have more than a modal inside a file, we would need to think about naming for longer than it is worth it

**Comment by PierreRambaud** [comment]
> I understand the reason, and I agree that we should have a different name for the file. btw. This is BC Break IMHO, because as you've noticed @SharakPL - overrides won't work anymore.
> 
> > Well, maybe it would be better to use filenames related to files' content, not the hooks they're supposed to be attached to ;)
> > ...as a general rule for modules.
> 
> This might be good for this scenario, but if you have more than a modal inside a file, we would need to think about naming for longer than it is worth it

We can maybe accept the BC break?

**Comment by SharakPL** [comment]
...or maybe add an upgrade script to rename/copy displayHeader.tpl to displayFooter.tpl if it is found in current theme's module overrides to fix BC break. Also I'm not sure it even should be in `displayFooter`, as this hook contains columns of footer links and data. `displayFooterAfter` could be better for this or better yet `displayWrapperTop` which on current classic theme is placed right after **notifications.tpl** is loaded.

**Comment by matks** [comment]
Argh I just come to this PR now 😅  and I see we really have an issue.

For anybody else curious:

@SharakPL wants to modify the filename to match the change did before. The hook used was changed so in order to keep it consistent.

But if we do this, if someone used template override on this module and upgrade the module the override will not be working anymore.

So the change is a good thing but it's a BC break (just like changing a PHP class name or a folder name).

I think this change is not worth releasing a new major version. 🤔 

I suggest what we do is: next time we build a new major version (major version = BC breaks allowed) we seize the opportunity to introduce this change. But we should not release a new major blockwishlist version just for this change, because there is no user value.

**Comment by SharakPL** [comment]
@matks I can live with that 😅

**Comment by matks** [comment]
@SharakPL Thanks !

And the idea is not to reject your contribution, rather to delay it until the right moment ;)

**Comment by SharakPL** [comment]
Your idea is perfectly clear and I agree 😉

**Comment by SharakPL** [comment]
Turns out placing this in `displayFooter` is very wrong:
1. This is hook for footer columns
2. Modals' styling is messed up by footer specific styles
3. Positioning and overlays are messed up by footer's z-index.

**It has to be placed at the bottom after the page layout, not inside it!**

**Pull request closed without merging**
