### PR TITLE
Set scrollbar from add to wishlist modal to auto

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | The scroll bar inside modal add to wishlist was always visible
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27142.
| How to test?      | See issue
| Possible impacts? | Add to wishlist modal

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I found a trivial issue using 178x branch & develop branch
image

**Without PR**
image

Thanks!

**Comment by NeOMakinG** [comment]
@khouloudbelguith It's not related to the PR but I fixed it, it's related to the footer style of classic

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Please check the Conflicting files.

Thanks!

**Review by PierreRambaud — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @NeOMakinG,

I checked with 178x branch & develop branch.
It is ok :heavy_check_mark: 
1. 178x + with no scroll
https://user-images.githubusercontent.com/16067358/152146102-eabe0eed-250b-4b3a-8142-4de610b1a439.mp4

2. 178x + with scroll
https://user-images.githubusercontent.com/16067358/152146452-f4e20f27-6bf8-470a-87cf-2a9fc9142af9.mp4

3. a mobile + arabic 
image
4. A mobile + French 
image

Thanks!

**Pull request merged**
