### PR TITLE
(WIP // Don't merge!) PrestaShop 1.7 compatibility

### PR DESCRIPTION
**Pull request by firstred**
screenshot from 2018-10-29 11-42-20

### CODE REVIEW

**Comment by GreatestShowman** [comment]
Hi ! How did you install this module ? I tryied to download by "clone as zip" but when I drag and drop it for install it don't works. I tryied to install it by FTP in "module" place but I don't see it at all. Could you help me ?

**Comment by GreatestShowman** [comment]
Hello, okay I arrived to install it but it's not compatible with prestashop 1.7.4.2 ! How can I download the most recent version with your modifications because the "master" fork were 2 years ago .. I would like to contribute. thks

**Comment by firstred** [comment]
```shell
$ git clone https://github.com/firstred/blockwishlist -b ps17
```
is the command you need to download the pull request

**Comment by GreatestShowman** [comment]
Hi ! I finally install it but is it normal i it's impossible to add & save a new wishlist, and add products ? I'm on prestashop 1.7.5.0

**Comment by kpodemski** [comment]
@firstred welcome... back?

**Pull request closed without merging**
