### PR TITLE
Use npm ci instead of npm install

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Use npm ci instead of npm install
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | -

### CODE REVIEW

**Comment by matks** [comment]
Hello @M0rgan01 what will happen to this PR 😉 ?

**Comment by M0rgan01** [comment]
@matks PHPStan (Latest) tests do not pass. Not related to PR changes. I have to see why. Before this there was a problem on the Build & Release draft stage.

**Comment by M0rgan01** [comment]
Now it's good ? :+1:

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by matks — COMMENTED** [review]
GitHub Action passed https://github.com/PrestaShop/blockwishlist/actions/runs/6747287451/job/18343084897?pr=225

Running `npm ci` will run `npm install` AND verify the CI?

**Comment by M0rgan01** [comment]
@matks 

The main differences between using npm install and npm ci are:

    - The project must have an existing package-lock.json or npm-shrinkwrap.json.
    - If dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead of updating the package lock.
    - npm ci can only install entire projects at a time: individual dependencies cannot be added with this command.
    - If a node_modules is already present, it will be automatically removed before npm ci begins its install.
    - It will never write to package.json or any of the package-locks: installs are essentially frozen.

**Review by matks — APPROVED** [review]
Thank you @M0rgan01

**Pull request merged**
