### PR TITLE
Attribute delete fix

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      |  Attribute deletion fix, currently hook is not working properly Related to https://github.com/PrestaShop/PrestaShop/pull/32475
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Added product with specific attribute combination to wishlist and then delete that attribute in BO, then that product should be removed from wishlist as well

### CODE REVIEW

**Comment by JevgenijVisockij** [comment]
Not sure if I should target dev or master

**Review by jolelievre — APPROVED** [review]
Thanks @JevgenijVisockij

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @JevgenijVisockij 

Thanks for your PR :rocket: 
Unfortunately, I'm unable to test your PR cause of this regression on dev branch https://github.com/PrestaShop/PrestaShop/issues/32844
I will put the label `Blocked` till the regression will be fixed.

Thanks!

**Review by matthieu-rolland — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by aniszr — COMMENTED** [review]
Hello @JevgenijVisockij 

I tested your PR with PS 8.1.1 & PS 8.0.5 :

-  **PS 8.1.1** & **PS 8.0.5**
The product added to the wishlist is not automatically deleted after deleting the combination attribute in BO

See attached screenrecord :

https://github.com/PrestaShop/blockwishlist/assets/92626242/c25c12b9-94fd-41f3-bcd3-cd1107634c59


Please check and feed-back !

Thanks!

**Review by djoelleuch — APPROVED** [review]
Hello @JevgenijVisockij  ,
Tested on PS 8.1.1

[Untitled_ Aug 10, 2023 11_49 AM.webm](https://github.com/PrestaShop/blockwishlist/assets/115152460/9dbd7755-7e68-4551-9e68-36ab4a6de6b7)


LGTM ,it's QA :heavy_check_mark:

Thank you  :rocket:  !

**Comment by lartist** [comment]
Thanks @JevgenijVisockij

**Pull request merged**
