### PR TITLE
Fix for Behavior while logout on wishlist is not consistent

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Redirect to the homepage when trying to access an unauthorized wishlist with the correct error message
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29654.
| How to test?      | Try to access `/module/blockwishlist/view?id_wishlist=1` when being logged off
| Possible impacts? | The blockwishlist module

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Looks sane 🍬

**Review by atomiix — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @0x346e3730 , 

Thanks for your PR. The issue is well fixed and I found no regression :tada: 

https://watch.screencastify.com/v/gr7B53imga45G1rHRu9p

**Comment by paulnoelcholot** [comment]
Hello @0x346e3730 , 

Thanks for your PR. The issue is well fixed and I found no regression :tada: 

https://watch.screencastify.com/v/gr7B53imga45G1rHRu9p

**Review by paulnoelcholot — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @0x346e3730 and @paulnoelcholot

**Pull request merged**
