### PR TITLE
v3.0.2

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | PR for release v3.0.2
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | PrestaShop SA 
| How to test?      | Test the whole module behaviours

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]
Approved for UI Tests

**Comment by matks** [comment]
A version long time due 😁

**Review by boherm — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @nicosomb ,

Tested the whole module on develop, 8.1.x and 8.0.x.

Bump to v3.0.2 OK.

In BO
- Configuration block OK ✅ 
- Statistics block NOK :x:

I have an exception after adding product into my wishlist.
`Warning: Undefined array key "category_name"` :
Screenshot 2024-09-02 at 17 21 43

In FO
- Creation of wish lists
- Addition of products on wish list
- Edition of combinations of products
- Add product to cart after putting it in the wishlist
- Delete all products in wish lists
- Delete/rename/share wish lists

Could you check the exception part ?
Thanks :D

**Comment by nicosomb** [comment]
@florine2623 I can't reproduce statistics and "add to wishlist" bug. Could you try again or tell me in details how I can reproduce them please?

**Comment by paulnoelcholot** [comment]
Hello @nicosomb,

I tested the PR and I found a bug.

image

Step to reproduce : 
On FO : 
- Sign in with a customer
- Add product to wishlist
- On BO : 
- Module > Blockwishlist > Statistics
- Error

**Comment by nicosomb** [comment]
it seems that these bugs are already in v3.0.1. So it's not related to this PR.

**Review by florine2623 — COMMENTED** [review]
Hello @nicosomb ,

Tested these bugs with v3.0.1 and branch dev.

I have some news errors not mentioned previously in this PR.

Following @paulnoelcholot 's comment, I have this error :

https://github.com/user-attachments/assets/4ed7f17b-ab30-4e8f-aa49-bf8685f6fe4f

Screenshot 2024-09-06 at 11 26 23

`The controller for URI "/modules/blockwishlist/statistics" is not callable: Controller "PrestaShop\Module\BlockWishList\Controller\WishlistConfigurationAdminController" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service?`

I don't think it's a good idea to validate this PR if it cannot be tested properly and if some big exceptions are displayed. Sorry 😭 

Maybe we should block this release until at least some of these errors are fixed ?
WDTY ?

**Comment by nicosomb** [comment]
@paulnoelcholot about your bug, there is already an opened issue https://github.com/PrestaShop/PrestaShop/issues/33374
This PR is not here to fix it, sorry.

**Comment by nicosomb** [comment]
@florine2623 the first bug is fixed in https://github.com/PrestaShop/blockwishlist/pull/280

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@florine2623 The core was merged, should be good to test. :-)

**Comment by florine2623** [comment]
Hello @nicosomb ,

I'm having some issues testing this PR again 😭 

Installation of PR is successful, BUT bump to v3.0.2 isn't taken into account. 
In FO, when I add a product to my wishlist in my customer account, I can't see the wishlists created nor the products added to it.

:/

Could this one be tested by a dev please ? 
Thanks :)

**Comment by boherm** [comment]
@florine2623, I will take care of it ;)

**Comment by boherm** [comment]
Hello @nicosomb!

After some tests for this `3.0.2` version:
- `develop`: 🟢
- `8.2.x`: 🟢
- `8.1.x`: 🟢
- `8.0.x`: 🟢

It works!

**Pull request merged**
