### PR TITLE
Remove unused class doing conflic with corejs

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | There was an error while sorting inside a product list of a wishlist
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27145.
| How to test?      | See issue
| Possible impacts? | Nothing

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,

I tested the PR and it seems that the issue is partially fixed.  The same error still observed when trying to go to the next page in the wishlist.
https://watch.screencastify.com/v/CJI3NeW2ZSFYODNrEHM4
@NeOMakinG Could you please check?

Many thanks,

**Comment by NeOMakinG** [comment]
@marwachelly fine now

**Comment by marwachelly** [comment]
Hello @NeOMakinG ,

Could you please check conflicting files? 

Many thanks,

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @marwachelly

**Pull request merged**
