### PR TITLE
Update delete modal wordings

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Translation of delete product from wishlist modal is pretty wrong, we wants to change it
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24402.
| How to test?      | Add a product to your wishlist, go to your wishlist, try to delete it, the modal should have the wording inside the issue
| Possible impacts? | Delete product modal wordings

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @NeOMakinG

**Comment by Robin-Fischer-PS** [comment]
Hi @NeOMakinG !

The wording is now OK : 
pr blockwishlist 118


Thanks ! QA :heavy_check_mark:

**Comment by NeOMakinG** [comment]
@Robin-Fischer-PS should be fixed now

**Comment by Robin-Fischer-PS** [comment]
Now it's OK on both product and list deletion : 

pr blockwishlist 118 list delete

So it's QA :heavy_check_mark: , thanks @NeOMakinG !

**Comment by NeOMakinG** [comment]
@jolelievre review and merge!

**Review by Progi1984 — APPROVED** [review]

**Pull request merged**
