### PR TITLE
Fix upgrade from previous versions

### PR DESCRIPTION
**Pull request by Matt75**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix fatal error when upgrading from previous versions
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24321
| How to test?      | Upgrade from previous version should works without Exception
| Possible impacts? | Module upgrade

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello @Matt75 
I didn't find the tag 1.3.2 of this module to test the PR. 
https://github.com/PrestaShop/blockwishlist/tags
Could you please provide me with the link to download this version.
Many thanks,

**Comment by Matt75** [comment]
Retrieved from PrestaShop Addons
[blockwishlist-1.3.2.zip](https://github.com/PrestaShop/blockwishlist/files/7544898/blockwishlist-1.3.2.zip)

**Comment by khouloudbelguith** [comment]
Hi @Matt75,

It is ok :heavy_check_mark: 

- I checked a simple shop / I check a multi-shop
- The upgrade of the module => ok
- I checked data added before upgrade => ok
- I added some new products to the wishlist 
- I removed some products from the wishlist => ok

https://watch.screencastify.com/v/n09wV1O0VEUKXo3qA5Z9

to test this PR, I followed these steps:
1. Install PS17612
2. Remove the module blockrss
3. I install the module blockwishlist v1.3.2
4. Upgrade to PS1781 using the 1-click upgrade v4.13.0
5. Go to BO > Modules > Module manage page > Upload the .zip of this PR 

[blockwishlist.zip](https://github.com/PrestaShop/blockwishlist/files/7597486/blockwishlist.zip)

Thanks!

**Comment by Progi1984** [comment]
Thanks @Matt75 & @khouloudbelguith

**Pull request merged**
