### PR TITLE
FO / Blockwishlist - bad display when wishlist name is too long in ta…

### PR DESCRIPTION
**Pull request by akrambak**
FO / Blockwishlist - bad display when wishlist name is too long in tablet/mobile screens #29213

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | FO / Blockwishlist - bad display when wishlist name is too long in tablet/mobile screens #29213
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#29213](https://github.com/PrestaShop/PrestaShop/issues/29213)
| Sponsor company   | Bakhouche Akram
| How to test?      | Front.

### CODE REVIEW

**Review by 0x346e3730 — CHANGES_REQUESTED** [review]
Hello @akrambak, thank you for your contribution. Your PR only changes a builded version of the javascript, however you should need to change the source file, now the builded one.

**Comment by akrambak** [comment]
> Hello @akrambak, thank you for your contribution. Your PR only changes a builded version of the javascript, however you should need to change the source file, now the builded one.

Hello, can you help me to find the path of the source file to change, a litle help, i will find it myself.

**Comment by mflasquin** [comment]
> > Hello @akrambak, thank you for your contribution. Your PR only changes a builded version of the javascript, however you should need to change the source file, now the builded one.
> 
> Hello, can you help me to find the path of the source file to change, a litle help, i will find it myself.

Hi @akrambak, you can see the wishlistcontainer is build with webpack, it contains files describes in .webpack/common.js :

`    wishlistcontainer: [
      './_dev/front/js/container/WishlistContainer',
      './_dev/front/js/components/Create',
      './_dev/front/js/components/Delete',
      './_dev/front/js/components/Toast',
      './_dev/front/js/components/Share',
      './_dev/front/js/components/Rename',
    ],`

So you have to update one of these file to fix the issue :smile:
It it clear ?

**Comment by akrambak** [comment]
@mflasquin It's clear thks
I pushed a new commit 9b6a769c1166bf4fdeee32c5c49c2d311145da87
Is it okay ?

@0x346e3730

**Comment by kpodemski** [comment]
@akrambak almost! seems that you compiled assets in the dev mode, only by running the watch, is that true? you should run a build, so that assets get minified during compilation :)

**Comment by akrambak** [comment]
> @akrambak almost! seems that you compiled assets in the dev mode, only by running the watch, is that true? you should run a build, so that assets get minified during compilation :)

For the first commit i edited the bundle compiled directly.
In the second commit i changed the source file.
I didn't compiled.

**Comment by akrambak** [comment]
@kpodemski i miss a ";" 
Now it compile correctly, new commit cc2d57fbc2f7dde440161cc63819b0e222bd4ebc

My Bad

**Review by kpodemski — APPROVED** [review]

**Comment by akrambak** [comment]
@kpodemski can you rerun the tests please ?

**Comment by kpodemski** [comment]
thanks @akrambak I re-run the tests, I think everything's ok with your PR

let's wait for QA to re-test it :)

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Thanks @akrambak ! No more exception displayed !

I have retested, but I still encounter the original issue. 

Your PR is well installed. I have rebuild the assets. Cleared cache from PS and from my browser. Am I missing something ?
```
cd _dev
rm -rf node_modules
npm i --verbose
npm run build
```

https://user-images.githubusercontent.com/16019289/229114223-31a89a74-b42e-49b4-9bcb-dd954fbacc5b.mov

**Comment by akrambak** [comment]
@kpodemski Plz relanche the again. 3ab14896fc7df58e7b98cd03afe79398345db77b
@florine2623 the ";" was the last problem.
This time it will be Ok

image

**Review by kpodemski — APPROVED** [review]

**Comment by akrambak** [comment]
@kpodemski a new commit with "LF"
41bd3617959e1d193b0caed8d2ad8c7dd95b2f5f

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @akrambak

**Review by florine2623 — APPROVED** [review]
Thanks @akrambak ,

It is looking good :)

Checked on multiple screens sizes (desktop, tablet and mobile), it always looks as expected !
The buttons still work as usual.

Screenshot 2023-03-31 at 15 34 22

Screenshot 2023-03-31 at 15 34 30

It is QA ✅ !

**Comment by kpodemski** [comment]
thank you @akrambak ! well done 👏🏻

**Pull request merged**
