### PR TITLE
Fix modal display block

### PR DESCRIPTION
**Pull request by rodriciru**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | In some occasions this modal it's on top of page, and cannot click on products, buttons....
| Type?             | bug fix 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28565
| How to test?      | Just check if modal create wish list its display block by default

PLEASE, I CANNOT TEST IT, BECAUSE I HAVE VS2022 AND THIS MODULE USES NODE-SASS V5 WHICH APART FROM Being DEPRECATED IT USES AN OLD NODE-GYP WHICH CANNOT RECOGNIZE VS2022 C++ BUILD TOOLS
ANYWAY, SUCH A SMALL CHANGE SHOULDN BE Too MUCH PROBLEM

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@rodriciru I guess it's testable with node directly? You shouldn't be blocked to test it

**Review by NeOMakinG — APPROVED** [review]

**Comment by rodriciru** [comment]
> @rodriciru I guess it's testable with node directly? You shouldn't be blocked to test it

Well i can even do a npm i because of old dependencies. At the end i update node-sass to v6 and it works.

**Review by sLorenzini — APPROVED** [review]
hello @rodriciru,

Tested on develop (8.x) and 1.7.8.x branches.
PHP version 7.2

Tested blockwishlist module:
- with **Classic theme** on homepage/category/product pages
on desktop, responsive and mobile screens
- with **Hummingbird theme** on homepage/category/product pages
on desktop, responsive and mobile screens

`display:block` attribute is removed when the modal is closed. All good 
 
QA approved ✅ 

Thanks

**Comment by Progi1984** [comment]
Thanks @rodriciru & @sLorenzini

**Pull request merged**
