### PR TITLE
Fix used params

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Params is not the good one.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaEdit are you sure about this ch,ange? In the database we keep `id_product_attribute`, above you have a method:

```
public function hookActionProductAttributeDelete(array $params)
```

I think we should look for all the combinations with the provided id_attribute in this method and delete them.

**Review by kpodemski — CHANGES_REQUESTED** [review]
Params are not good, but the logic behind this method seems to be wrong as the second parameter accepts `id_product_attribute`

**Comment by matks** [comment]
> Params are not good, but the logic behind this method seems to be wrong as the second parameter accepts `id_product_attribute`

I am sorry @kpodemski but can you explain ? 😅 I did not understand this

**Comment by kpodemski** [comment]
@matks 

`id_attribute` is a id of the single Attribute, `id_product_attribute` is a ID for the combination of those

**Pull request closed without merging**
