### PR TITLE
v3.0.1

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | PR for release v3.0.1
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | Test the whole module behaviours

### CODE REVIEW

**Comment by djoelleuch** [comment]
Hello @lartist ,

I found an issue that was not correct related to this this [PR](https://github.com/PrestaShop/blockwishlist/pull/191):
when you make changes in the wishlist configuration especially for the Wishlist default title .


- steps to reproduce:

1. go to modules > module manager > search for the wishlist module
2. choose the french language > change the Wishlist default title to "Wishlist" then click on save .
3.   FO create a new customer > choose a product to add to the wishlist > see the wishlist the Wishlist default title is changing .
4. try to change the language [EN ] > SEE same Wishlist default title !! 

See the screen record for more informations : 

[Untitled_ Aug 10, 2023 6_00 PM.webm](https://github.com/PrestaShop/blockwishlist/assets/115152460/f958206f-c0ae-40ef-a953-af605869e484)

Could you please check it 

Thanks

**Comment by MatShir** [comment]
Thanks for the test @djoelleuch. The bug is still semi-persistent so it's not really blocking the release. There are other fix worth the release. We will fix this issue on another release ;)
Could you make a dedicated issue ? 
@lartist go release. !

**Comment by lartist** [comment]
Thanks @lartist

**Review by jolelievre — APPROVED** [review]
Thanks @lartist

**Pull request merged**
