### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 2.1.0
| Type?             | improvement

Notice for QA team: when this PR is merged please check issue https://github.com/PrestaShop/PrestaShop/issues/27119 is fixed

### CODE REVIEW

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I found one regression in this release: https://github.com/PrestaShop/PrestaShop/issues/27135
As discussed with @Robin-Fischer-PS, this release blocks the develop branch, so we will accept the release but we need to create another release to fix this issue soon.

I found other issues when testing the release but they are not regressions:
https://github.com/PrestaShop/PrestaShop/issues/27128
https://github.com/PrestaShop/PrestaShop/issues/27131
https://github.com/PrestaShop/PrestaShop/issues/27134
https://github.com/PrestaShop/PrestaShop/issues/27136
https://github.com/PrestaShop/PrestaShop/issues/27140
https://github.com/PrestaShop/PrestaShop/issues/27142
https://github.com/PrestaShop/PrestaShop/issues/27143
https://github.com/PrestaShop/PrestaShop/issues/27144
https://github.com/PrestaShop/PrestaShop/issues/27145

Thank you!

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud,
> 
> I found one regression in this release: [PrestaShop/PrestaShop#27135](https://github.com/PrestaShop/PrestaShop/issues/27135) As discussed with @Robin-Fischer-PS, this release blocks the develop branch, so we will accept the release but we need to create another release to fix this issue soon.
> 
> I found other issues when testing the release but they are not regressions: [PrestaShop/PrestaShop#27128](https://github.com/PrestaShop/PrestaShop/issues/27128) [PrestaShop/PrestaShop#27131](https://github.com/PrestaShop/PrestaShop/issues/27131) [PrestaShop/PrestaShop#27134](https://github.com/PrestaShop/PrestaShop/issues/27134) [PrestaShop/PrestaShop#27136](https://github.com/PrestaShop/PrestaShop/issues/27136) [PrestaShop/PrestaShop#27140](https://github.com/PrestaShop/PrestaShop/issues/27140) [PrestaShop/PrestaShop#27142](https://github.com/PrestaShop/PrestaShop/issues/27142) [PrestaShop/PrestaShop#27143](https://github.com/PrestaShop/PrestaShop/issues/27143) [PrestaShop/PrestaShop#27144](https://github.com/PrestaShop/PrestaShop/issues/27144) [PrestaShop/PrestaShop#27145](https://github.com/PrestaShop/PrestaShop/issues/27145)
> 
> Thank you!

We don't care about the develop branch when a module release can affect websites in production.
We have to fix all issues first!

**Review by matthieu-rolland — COMMENTED** [review]
I agree with @PierreRambaud , we shouldn't release the module until the regression is fixed 

thank you for your feedback @khouloudbelguith 👍

**Comment by matks** [comment]
> PrestaShop/PrestaShop#27144

Update:

Only 3 issues remain open
https://github.com/PrestaShop/PrestaShop/issues/27142
https://github.com/PrestaShop/PrestaShop/issues/27143
https://github.com/PrestaShop/PrestaShop/issues/27144

**Comment by florine2623** [comment]
Hello @PierreRambaud ,

After further testing with @khouloudbelguith , here is what we found :

3 regressions :
https://github.com/PrestaShop/PrestaShop/issues/27478
https://github.com/PrestaShop/PrestaShop/issues/27327
https://github.com/PrestaShop/PrestaShop/issues/26349
Other issues : 
https://github.com/PrestaShop/PrestaShop/issues/27488
https://github.com/PrestaShop/PrestaShop/issues/27474

**Comment by SharakPL** [comment]
How much longer until new release? It's hard to use this module in current state.

**Review by Progi1984 — APPROVED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hi @Robin-Fischer-PS, @PrestaShop/prestashop-maintainers,

I checked this release with 178x & develop branch
I re-opened those issues:
- https://github.com/PrestaShop/PrestaShop/issues/27478#issuecomment-1087711583: fixed only in the develop, but it is nok with 178x (major regression module because 1785 + v2.0.1 => ok)
- https://github.com/PrestaShop/PrestaShop/issues/27140#issuecomment-1087682117: minor regression module v2.1.0
- https://github.com/PrestaShop/PrestaShop/issues/27135#issuecomment-1087451365: trivial regression module v2.1.0

I found those issues:
- https://github.com/PrestaShop/PrestaShop/issues/28131 minor regression 178
- https://github.com/PrestaShop/PrestaShop/issues/28130 major bug but not a regression

What do you think?
We need to fix those issues or we accept the release.

Thanks you!

**Review by matks — CHANGES_REQUESTED** [review]
QA team found issues

**Review by khouloudbelguith — COMMENTED** [review]
Hi @PrestaShop/prestashop-maintainers,

I found a critical regression on the develop branch following these steps:
1. Install the develop branch
2. Go to BO > Modules > Module manager page 
3. Uninstall the old version of the module blockwishlist v2.0.1 with removing the folder
4. Install the release and during the install => open another page from BO in another tab
5. An exception is displayed
6. Click on configure of the module => exception
7. All the BO is NOK now

I attached a screen record

https://user-images.githubusercontent.com/16067358/163567496-2c83b052-a5e0-4cc7-b172-708f44d34b15.mp4

I checked v2.0.1 => ok

https://user-images.githubusercontent.com/16067358/163567512-f6654d2f-8f87-4063-b152-f2e84bcc746e.mp4

Thanks!

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud, @Progi1984,

It is ok :heavy_check_mark: 
I checked this release with 1.7.8x & develop branch

I have some issues but they are not regressions

- https://github.com/PrestaShop/PrestaShop/issues/28325
- https://github.com/PrestaShop/PrestaShop/issues/28326
- https://github.com/PrestaShop/PrestaShop/issues/28324

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith

**Pull request merged**
