### PR TITLE
Remove harmful modal styles and fix product buttons

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | These styles caused modals to be always active on the page, just invisible. This blocked elements behind modals from interaction.<br><br>Product buttons in wishlists didn't get proper styling, because of invalid checks.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/hummingbird/issues/594 https://github.com/PrestaShop/PrestaShop/issues/35276
| Sponsor company   | -
| How to test?      | 1. Install Hummingbird theme<br>2. Sign in and add few products to your wishlists<br>3. Go to My Account > My wishlists

Check that elements in the center of the browser screen can't be accessed because invisible modal is hanging there:

obraz

There are already styles for modals so inline vue overrides are useless here
https://github.com/PrestaShop/blockwishlist/blob/dbaf532ed79a920c2522545d4fabd476ce17808f/_dev/front/scss/_modal.scss#L19-L29

___
As for the buttons, these checks simply don't work and are always false because `product.customizable` is an INT, not a STRING:
https://github.com/PrestaShop/blockwishlist/blob/dbaf532ed79a920c2522545d4fabd476ce17808f/_dev/front/js/components/Product/Product.vue#L118-L121

Examples for Classic and Hummingbird themes:

### Before
obraz
obraz

### After
obraz
obraz

### CODE REVIEW

**Comment by leemyongpakva** [comment]
@SharakPL I made an related issue at PrestaShop/PrestaShop/issues/35365.For the second issue

**Comment by SharakPL** [comment]
@leemyongpakva are you certain that you implemented all the changes correctly?

https://github.com/PrestaShop/blockwishlist/assets/5007456/ed53bd69-5d2e-4c85-9f21-a35bd6973e69

**Comment by leemyongpakva** [comment]
@SharakPL I tested with these steps
`rm -rf blockwishlist`
`git clone https://github.com/PrestaShop/blockwishlist.git`
`gh pr checkout 239`
`cd blockwishlist`
`npm run build`
BO clear PS cache & FO clear browser cache
After PS: the first issue is solved but I encounter the second issue in a different style: all products are Customize.
Before PR: I don't see the second issue.

**Comment by SharakPL** [comment]
Maybe all the products on your wishlist are customizable 🤔

**Comment by SharakPL** [comment]
> `rm -rf blockwishlist`
> `git clone https://github.com/PrestaShop/blockwishlist.git`
> `gh pr checkout 239`
> `cd blockwishlist`
> `npm run build`

Wrong steps @leemyongpakva ! You did pr checkout inside modules instead of modules/blockwishlist so you probably checked out https://github.com/PrestaShop/PrestaShop/pull/239 😉

Try like this:
1. `cd modules`
2. `rm -rf blockwishlist`
3. `git clone https://github.com/PrestaShop/blockwishlist.git`
4. `cd blockwishlist`
5. `gh pr checkout 239`
6. `npm i` *
7. `npm run build` *
* 6-7 are obsolete really since all assets are pre-built in this module so PR already includes everything

### before
obraz

### after
obraz

**Comment by leemyongpakva** [comment]
@SharakPL You're right about Step 4 @ Step 5 order :thumbsup: By the way, with these correct steps, all Product buttons are still Customize (FYI, I use sample data of a fresh PS 8.1 install and there is only one Customizable product - Customizable mug).
I think creating a separate issue for **Product buttons in wishlists didn't get proper styling, because of invalid checks** will be better. That way, QA team can confirm the issue exist or not (I even don't see the issue with Product buttons from my side :)

**Comment by SharakPL** [comment]
OK let me check it out. I only tested it on develop branch.

**Comment by SharakPL** [comment]
@leemyongpakva I checked branch 8.1.x (basically 8.1.5 soon to be released) on php 8.1 and Classic theme v.2.1.3

### before PR
obraz

### after PR
obraz

So it's all good! I really have no idea why would you get all buttons labeled `Customize`

**Comment by leemyongpakva** [comment]
@SharakPL I see your view. We need a third view from QA. If they can reproduce the second issue then we can ignore my different view ;)

**Comment by SharakPL** [comment]
I'll take your advice and make 2 separate PRs of this.
Also I won't include compiled assets - them being included in the repo instead of .gitignored misled me into thinking they are required for each PR 🤦‍♂️

**Pull request closed without merging**
