### PR TITLE
Change assets priorities to permit override

### PR DESCRIPTION
**Pull request by henri9813**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This Merge request gonna permit css override from a theme.
| Type?             | improvement 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/24392
| How to test ? | Verify if blockwishlist functionalities works as usual (heart button, my wishlist pages...)
| Possible impacts? | None.

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Hello @henri9813, and thanks for you're contribution

@PrestaShop/prestashop-maintainers wdyt? I don't even know how that priority thing works myself :/

**Comment by kpodemski** [comment]
Priority is one thing (basically it's `position` of sorting in assets foreach), but maybe it would be good to give us example where exactly there's a problem with CSS and its specificity?

**Comment by Progi1984** [comment]
@henri9813 We are waiting for that your issue is validated before continuing the review. Thanks

**Comment by henri9813** [comment]
Hello,

For example, i wamt to apply this CSS:
```
.wishlist-footer-links>a,
.wishlist-add-to-new,
.wishlist-add-to-new i,
.wishlist-list-item:hover .wishlist-list-item-title {
  color: red !important;
}
```

If priorities are not set, my code is not  applied.

**Comment by NeOMakinG** [comment]
Should we make it tested by QA? I doubt about that

**Comment by Progi1984** [comment]
May be @NeOMakinG can answer to you

**Comment by NeOMakinG** [comment]
> @Progi1984 This solution is maybe not the best one.
> 
> I have a question, why the module inject color definition ? Why it doesn't just use the parent color ? ( no define ).?
> 
> This could resolve all the problems.
> 
> Maybe to do in 2nd step no ?

I don't really remember, as it was some months ago, but I think it's because the color wasn't fine, but if the parent color is the primary one, we could switch all of these into a `color: inherit` property

**Comment by henri9813** [comment]
This could be better.

In the wait, could you merge my merge-request please ?

Best regards

**Comment by NeOMakinG** [comment]
Tested it and it looks fine, thanks @henri9813

**Pull request merged**
