### PR TITLE
Fix getting cover on 1.7.6

### LINKED ISSUE #24021: [blockwishlist] No images available for my favorite products for blockwishlist v2 and 1.7.6
#### Describe the bug

When I add products to my wishlist and then go to the favorites list, my products are displayed but the product image is missing.

#### Expected behavior

I should have the product image displayed 

#### Steps to Reproduce

1. Go to the front office, 
2. Click on the heart either directly on the product block or in the product sheet to add the product to your favorites list 
3. Go to my account >  My wishlists  > the wishlist where I added my products 
4. I can see all the products added but without their image 

image

#### Additional information

* PrestaShop version: 1.7.6.7

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | `default_image` is not available on < 1.7.7
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24021
| How to test?      | Details in https://github.com/PrestaShop/PrestaShop/issues/24021 , To the QA: Test it on 1.7.6 specially
| Possible impacts? | n/a
| Sponsor company | impSolutions

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @kpodemski 

I try with PrestaShop 1.7.6.9 but images aren't displayed : 
Capture d’écran 2021-04-23 à 09 25 31
I try with a fresh install, I clean all caches, regenerate images maybe I'm missing something ?

**Comment by kpodemski** [comment]
Hello @sarahdib 

Did you rebuild js/css with `npm run build`?

**Comment by NeOMakinG** [comment]
@kpodemski we reverted the fact that we wasn't pushing assets in order to deliver it to everyone needing it (CI and anything else)

Could you push assets to it?

**Comment by kpodemski** [comment]
@NeOMakinG done

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @kpodemski & @sarahdib

**Pull request merged**
